name: Contribution Snake

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build_snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate snake svg
        uses: platane/snk@v0.6.0
        with:
          output: output/github-contribution-grid-snake-dark.svg
      - name: Commit snake SVG
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add output/github-contribution-grid-snake-dark.svg
          git commit -m "chore: update snake"
          git push